In [60]:
# Import libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
# Import dataset 
df = pd.read_csv(r"C:/Users/KIIT/Desktop/MLOPs/electricitybills/dataset/electricity_bill_dataset.csv")
df.head()

,Fan,Refrigerator,AirConditioner,Television,Month,City,Company,MonthlyHours,TariffRate,ElectricityBill,season,TotalApplianceHours,UsageCategory
0,16,23.0,2.0,6.0,10,Hyderabad,Tata Power Company Ltd.,384,8.4,3225.6,Winter,48.0,Medium
1,19,22.0,2.0,3.0,5,Vadodara,NHPC,488,7.8,3806.4,Summer,47.0,Medium
2,7,22.0,3.0,21.0,6,Mumbai,Power Grid Corp,475,9.2,4370.0,Monsoon,54.0,Medium
3,11,23.0,2.0,11.0,2,Mumbai,Ratnagiri Gas and Power Pvt. Ltd. (RGPPL),457,9.2,4204.4,Winter,48.0,Medium
4,13,22.0,0.0,18.0,6,Ratnagiri,Adani Power Ltd.,471,7.4,3485.4,Monsoon,54.0,Medium

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34654 entries, 0 to 34653
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Fan                  34654 non-null  int64
 1   Refrigerator         34654 non-null  float64
 2   AirConditioner       34654 non-null  float64
 3   Television           34654 non-null  float64
 4   Month                34654 non-null  int64
 5   City                 34654 non-null  object
 6   Company              34654 non-null  object
 7   MonthlyHours         34654 non-null  int64
 8   TariffRate           34654 non-null  float64
 9   ElectricityBill      34654 non-null  float64
 10  season               34654 non-null  object
 11  TotalApplianceHours  34654 non-null  float64
 12  UsageCategory        34654 non-null  object
dtypes: float64(6), int64(3), object(4)
memory usage: 3.4+ MB

In [63]:
# Dictionary for renaming columns
column_names = {
    'AirConditioner': 'Air Conditioner',
    'MotorPump': 'Motor Pump',
    'MonthlyHours': 'Monthly Hours',
    'TariffRate': 'Tariff Rate',
    'ElectricityBill': 'Electricity Bill',

}

# Rename columns using the dictionary
df = df.rename(columns=column_names)

# Display
df.head()

,Fan,Refrigerator,Air Conditioner,Television,Month,City,Company,Monthly Hours,Tariff Rate,Electricity Bill,season,TotalApplianceHours,UsageCategory
0,16,23.0,2.0,6.0,10,Hyderabad,Tata Power Company Ltd.,384,8.4,3225.6,Winter,48.0,Medium
1,19,22.0,2.0,3.0,5,Vadodara,NHPC,488,7.8,3806.4,Summer,47.0,Medium
2,7,22.0,3.0,21.0,6,Mumbai,Power Grid Corp,475,9.2,4370.0,Monsoon,54.0,Medium
3,11,23.0,2.0,11.0,2,Mumbai,Ratnagiri Gas and Power Pvt. Ltd. (RGPPL),457,9.2,4204.4,Winter,48.0,Medium
4,13,22.0,0.0,18.0,6,Ratnagiri,Adani Power Ltd.,471,7.4,3485.4,Monsoon,54.0,Medium

In [64]:
# df.to_csv('Home Electricity Bill Prediction.csv', index=False)

In [65]:
# Loop through each column and print the count of categorical values
for col in df.columns:
    if df[col].dtype == 'object':  # Check if column data type is object (categorical)
        print(f"Column '{col}' categorical values count:")
        print(df[col].value_counts())
        print('===========================================')

Column 'City' categorical values count:
City
Hyderabad      2255
Navi Mumbai    2226
Faridabad      2211
Gurgaon        2206
New Delhi      2200
Ratnagiri      2188
Dahej          2176
Mumbai         2168
Pune           2149
Noida          2146
Nagpur         2139
Chennai        2138
Ahmedabad      2136
Kolkata        2117
Shimla         2116
Vadodara       2083
Name: count, dtype: int64
===========================================
Column 'Company' categorical values count:
Company
Ringfeder Power Transmission India Pvt. Ltd.                          1142
Guj Ind Power                                                         1139
JSW Energy Ltd.                                                       1136
NTPC Pvt. Ltd.                                                        1135
Maha Transco – Maharashtra State Electricity Transmission Co, Ltd.    1133
Optibelt Power Transmission India Private Limited                     1125
Reliance Power                                                        1111
SJVN Ltd.                                                             1107
Neueon Towers / Sujana Towers Ltd.                                    1101
Kalpataru Power                                                       1100
GE T&D India Limited                                                  1099
Adani Power Ltd.                                                      1094
Torrent Power Ltd.                                                    1091
Power Grid Corp                                                       1087
NLC India                                                             1081
KEC International                                                     1080
Orient Green                                                          1080
L&T Transmission & Distribution                                       1079
Unitech Power Transmission Ltd.                                       1076
Bonfiglioli Transmission Pvt. Ltd.                                    1073
Sterlite Power Transmission Ltd                                       1073
Jyoti Structure                                                       1072
Jaiprakash Power                                                      1070
Ratnagiri Gas and Power Pvt. Ltd. (RGPPL)                             1068
Sunil Hitech Eng                                                      1067
NHPC                                                                  1066
TransRail Lighting                                                    1054
CESC                                                                  1035
Toshiba Transmission & Distribution Systems (India) Pvt. Ltd.         1028
Indowind Energy                                                       1027
Tata Power Company Ltd.                                               1019
Reliance Energy                                                       1006
Name: count, dtype: int64
===========================================
Column 'season' categorical values count:
season
Winter     14248
Monsoon    11756
Summer      8650
Name: count, dtype: int64
===========================================
Column 'UsageCategory' categorical values count:
UsageCategory
Medium    25525
High       7770
Low        1359
Name: count, dtype: int64
===========================================

### One hot Encoding

In [66]:
from sklearn.preprocessing import OneHotEncoder

# Create a list of columns to encode
categorical_columns = ['City', 'Company']

# Create a copy of the DataFrame with the selected columns
data = df.copy()

# Create an instance of OneHotEncoder
# sparse=False to produce a dense array and drop='first' to drop the first category of each variable
encoder = OneHotEncoder(sparse_output=False, drop='first')

# Iterate through each categorical column

for column in categorical_columns:
    # Fit and transform the selected column
    one_hot_encoded = encoder.fit_transform(data[[column]])

    # Create a DataFrame with one-hot encoded columns
    one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out([column]))

    # Concatenate the one-hot encoded DataFrame with the original DataFrame
    data = pd.concat([data, one_hot_df], axis=1)

    # Drop the original categorical column
    data = data.drop([column], axis=1)

# Display the resulting DataFrame
df = data.copy()

df.head()

,Fan,Refrigerator,Air Conditioner,Television,Month,Monthly Hours,Tariff Rate,Electricity Bill,season,TotalApplianceHours,...,Company_Reliance Power,Company_Ringfeder Power Transmission India Pvt. Ltd.,Company_SJVN Ltd.,Company_Sterlite Power Transmission Ltd,Company_Sunil Hitech Eng,Company_Tata Power Company Ltd.,Company_Torrent Power Ltd.,Company_Toshiba Transmission & Distribution Systems (India) Pvt. Ltd.,Company_TransRail Lighting,Company_Unitech Power Transmission Ltd.
0,16,23.0,2.0,6.0,10,384,8.4,3225.6,Winter,48.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,19,22.0,2.0,3.0,5,488,7.8,3806.4,Summer,47.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7,22.0,3.0,21.0,6,475,9.2,4370.0,Monsoon,54.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,11,23.0,2.0,11.0,2,457,9.2,4204.4,Winter,48.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,13,22.0,0.0,18.0,6,471,7.4,3485.4,Monsoon,54.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34654 entries, 0 to 34653
Data columns (total 57 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Fan                                                                         34654 non-null  int64
 1   Refrigerator                                                                34654 non-null  float64
 2   Air Conditioner                                                             34654 non-null  float64
 3   Television                                                                  34654 non-null  float64
 4   Month                                                                       34654 non-null  int64
 5   Monthly Hours                                                               34654 non-null  int64
 6   Tariff Rate                                                                 34654 non-null  float64
 7   Electricity Bill                                                            34654 non-null  float64
 8   season                                                                      34654 non-null  object
 9   TotalApplianceHours                                                         34654 non-null  float64
 10  UsageCategory                                                               34654 non-null  object
 11  City_Chennai                                                                34654 non-null  float64
 12  City_Dahej                                                                  34654 non-null  float64
 13  City_Faridabad                                                              34654 non-null  float64
 14  City_Gurgaon                                                                34654 non-null  float64
 15  City_Hyderabad                                                              34654 non-null  float64
 16  City_Kolkata                                                                34654 non-null  float64
 17  City_Mumbai                                                                 34654 non-null  float64
 18  City_Nagpur                                                                 34654 non-null  float64
 19  City_Navi Mumbai                                                            34654 non-null  float64
 20  City_New Delhi                                                              34654 non-null  float64
 21  City_Noida                                                                  34654 non-null  float64
 22  City_Pune                                                                   34654 non-null  float64
 23  City_Ratnagiri                                                              34654 non-null  float64
 24  City_Shimla                                                                 34654 non-null  float64
 25  City_Vadodara                                                               34654 non-null  float64
 26  Company_Bonfiglioli Transmission Pvt. Ltd.                                  34654 non-null  float64
 27  Company_CESC                                                                34654 non-null  float64
 28  Company_GE T&D India Limited                                                34654 non-null  float64
 29  Company_Guj Ind Power                                                       34654 non-null  float64
 30  Company_Indowind Energy                                                     34654 non-null  float64
 31  Company_JSW Energy Ltd.                                                     34654 non-null  float64
 32  Company_Jaiprakash Power                                                    34654 non-null  float64
 33  Company_Jyoti Structure                                                     34654 non-null  float64
 34  Company_KEC International                                                   34654 non-null  float64
 35  Company_Kalpataru Power                                                     34654 non-null  float64
 36  Company_L&T Transmission & Distribution                                     34654 non-null  float64
 37  Company_Maha Transco – Maharashtra State Electricity Transmission Co, Ltd.  34654 non-null  float64
 38  Company_NHPC                                                                34654 non-null  float64
 39  Company_NLC India                                                           34654 non-null  float64
 40  Company_NTPC Pvt. Ltd.                                                      34654 non-null  float64
 41  Company_Neueon Towers / Sujana Towers Ltd.                                  34654 non-null  float64
 42  Company_Optibelt Power Transmission India Private Limited                   34654 non-null  float64
 43  Company_Orient Green                                                        34654 non-null  float64
 44  Company_Power Grid Corp                                                     34654 non-null  float64
 45  Company_Ratnagiri Gas and Power Pvt. Ltd. (RGPPL)                           34654 non-null  float64
 46  Company_Reliance Energy                                                     34654 non-null  float64
 47  Company_Reliance Power                                                      34654 non-null  float64
 48  Company_Ringfeder Power Transmission India Pvt. Ltd.                        34654 non-null  float64
 49  Company_SJVN Ltd.                                                           34654 non-null  float64
 50  Company_Sterlite Power Transmission Ltd                                     34654 non-null  float64
 51  Company_Sunil Hitech Eng                                                    34654 non-null  float64
 52  Company_Tata Power Company Ltd.                                             34654 non-null  float64
 53  Company_Torrent Power Ltd.                                                  34654 non-null  float64
 54  Company_Toshiba Transmission & Distribution Systems (India) Pvt. Ltd.       34654 non-null  float64
 55  Company_TransRail Lighting                                                  34654 non-null  float64
 56  Company_Unitech Power Transmission Ltd.                                     34654 non-null  float64
dtypes: float64(52), int64(3), object(2)
memory usage: 15.1+ MB

## Import Necessary libraries for building the model

In [68]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor, GradientBoostingRegressor
from lightgbm import LGBMRegressor
from sklearn.svm import SVR
from catboost import CatBoostRegressor
from xgboost.sklearn import XGBRegressor

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
# Evaluation 
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [69]:
%pip install pandas flask joblib scikit-learn

Requirement already satisfied: pandas in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (2.3.3)
Requirement already satisfied: flask in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (3.1.2)
Requirement already satisfied: joblib in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (1.5.3)
Requirement already satisfied: scikit-learn in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.23.2 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: blinker>=1.9.0 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from flask) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from flask) (3.1.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: colorama in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from click>=8.1.3->flask) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\kiit\miniconda3\envs\elec_bill\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Define the features and target variable 

# drop null values
df = df.dropna()
# 
# Features 
X = df.drop(columns={'Electricity Bill'})

# Target variable 
y = df['Electricity Bill']

In [71]:
# Training set and testing split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [79]:
# Initialize the standard scaler
# scaler = StandardScaler()

# Fit and transform the training data
# X_train_scaled = scaler.fit_transform(X_train)

# Transform the testing data
# X_test_scaled = scaler.transform(X_test)

num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X_train.select_dtypes(include=['object']).columns

print("Numeric columns:", num_cols)
print("Categorical columns:", cat_cols)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ]
)

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(random_state=42))
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

Numeric columns: Index(['Fan', 'Refrigerator', 'Air Conditioner', 'Television', 'Month',
       'Monthly Hours', 'Tariff Rate', 'TotalApplianceHours', 'City_Chennai',
       'City_Dahej', 'City_Faridabad', 'City_Gurgaon', 'City_Hyderabad',
       'City_Kolkata', 'City_Mumbai', 'City_Nagpur', 'City_Navi Mumbai',
       'City_New Delhi', 'City_Noida', 'City_Pune', 'City_Ratnagiri',
       'City_Shimla', 'City_Vadodara',
       'Company_Bonfiglioli Transmission Pvt. Ltd.', 'Company_CESC',
       'Company_GE T&D India Limited', 'Company_Guj Ind Power',
       'Company_Indowind Energy', 'Company_JSW Energy Ltd.',
       'Company_Jaiprakash Power', 'Company_Jyoti Structure',
       'Company_KEC International', 'Company_Kalpataru Power',
       'Company_L&T Transmission & Distribution',
       'Company_Maha Transco – Maharashtra State Electricity Transmission Co, Ltd.',
       'Company_NHPC', 'Company_NLC India', 'Company_NTPC Pvt. Ltd.',
       'Company_Neueon Towers / Sujana Towers Ltd.',
       'Company_Optibelt Power Transmission India Private Limited',
       'Company_Orient Green', 'Company_Power Grid Corp',
       'Company_Ratnagiri Gas and Power Pvt. Ltd. (RGPPL)',
       'Company_Reliance Energy', 'Company_Reliance Power',
       'Company_Ringfeder Power Transmission India Pvt. Ltd.',
       'Company_SJVN Ltd.', 'Company_Sterlite Power Transmission Ltd',
       'Company_Sunil Hitech Eng', 'Company_Tata Power Company Ltd.',
       'Company_Torrent Power Ltd.',
       'Company_Toshiba Transmission & Distribution Systems (India) Pvt. Ltd.',
       'Company_TransRail Lighting',
       'Company_Unitech Power Transmission Ltd.'],
      dtype='object')
Categorical columns: Index(['season', 'UsageCategory'], dtype='object')

### XGBRegressor

In [80]:

def model(X_train_scaled, y_train, X_test_scaled, y_test):
    # Initialize the XGBRegressor model
    xgb_model = XGBRegressor()

    # Fit the model on the entire training data
    xgb_model.fit(X_train_scaled, y_train)

    # Make predictions on the testing data
    y_pred = xgb_model.predict(X_test_scaled)

    # Evaluate the model on the testing data
    mae_test = mean_absolute_error(y_test, y_pred)
    r2_test = r2_score(y_test, y_pred)
    mape_test = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    mse_test = mean_squared_error(y_test, y_pred)
    rmse_test = np.sqrt(mse_test)

    # Return the evaluation metrics
    return mae_test, r2_test, mape_test, mse_test, rmse_test

# Assuming you have defined X_train_scaled, y_train, X_test_scaled, and y_test
mae_test, r2_test, mape_test, mse_test, rmse_test = model(X_train_scaled, y_train, X_test_scaled, y_test)

print("MAE:", mae_test)
print("R2:", r2_test)
print("MAPE:", mape_test)
print("MSE:", mse_test)
print("RMSE:", rmse_test)

MAE: 9.828995152975534
R2: 0.9997032384346682
MAPE: 0.2653203033585393
MSE: 293.1628834252662
RMSE: 17.12199998321651

### CatBoostRegressor

In [81]:
def model(X_train_scaled, y_train, X_test_scaled, y_test):
   
    ct_model = CatBoostRegressor(verbose=0)

    # Fit the model on the entire training data
    ct_model.fit(X_train_scaled, y_train)

    # Make predictions on the testing data
    y_pred = ct_model.predict(X_test_scaled)

    # Evaluate the model on the testing data
    mae_test = mean_absolute_error(y_test, y_pred)
    r2_test = r2_score(y_test, y_pred)
    mape_test = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    mse_test = mean_squared_error(y_test, y_pred)
    rmse_test = np.sqrt(mse_test)

    # Return the evaluation metrics
    return mae_test, r2_test, mape_test, mse_test, rmse_test

mae_test, r2_test, mape_test, mse_test, rmse_test = model(X_train_scaled, y_train, X_test_scaled, y_test)

print("MAE:", mae_test)
print("R2:", r2_test)
print("MAPE:", mape_test)
print("MSE:", mse_test)
print("RMSE:", rmse_test)

MAE: 7.781515348814935
R2: 0.9997958386205997
MAPE: 0.21663023552070337
MSE: 201.6856145173078
RMSE: 14.201606054151334

### RandomForestRegressor

In [82]:
def model(X_train_scaled, y_train, X_test_scaled, y_test):
   
    rf_model = RandomForestRegressor()

    # Fit the model on the entire training data
    rf_model.fit(X_train_scaled, y_train)

    # Make predictions on the testing data
    y_pred = rf_model.predict(X_test_scaled)

    # Evaluate the model on the testing data
    mae_test = mean_absolute_error(y_test, y_pred)
    r2_test = r2_score(y_test, y_pred)
    mape_test = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    mse_test = mean_squared_error(y_test, y_pred)
    rmse_test = np.sqrt(mse_test)

    # Return the evaluation metrics
    return mae_test, r2_test, mape_test, mse_test, rmse_test


mae_test, r2_test, mape_test, mse_test, rmse_test = model(X_train_scaled, y_train, X_test_scaled, y_test)

print("MAE:", mae_test)
print("R2:", r2_test)
print("MAPE:", mape_test)
print("MSE:", mse_test)
print("RMSE:", rmse_test)

MAE: 1.886718366758463
R2: 0.9999719928245283
MAPE: 0.055448581489203716
MSE: 27.667546195499177
RMSE: 5.2599948855012375

### DecisionTreeRegressor

In [83]:

def model(X_train_scaled, y_train, X_test_scaled, y_test):
    
    dt_model = DecisionTreeRegressor()

    # Fit the model on the entire training data
    dt_model.fit(X_train_scaled, y_train)

    # Make predictions on the testing data
    y_pred = dt_model.predict(X_test_scaled)

    # Evaluate the model on the testing data
    mae_test = mean_absolute_error(y_test, y_pred)
    r2_test = r2_score(y_test, y_pred)
    mape_test = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    mse_test = mean_squared_error(y_test, y_pred)
    rmse_test = np.sqrt(mse_test)

    # Return the evaluation metrics
    return mae_test, r2_test, mape_test, mse_test, rmse_test

# Example usage:
# Assuming you have defined X_train_scaled, y_train, X_test_scaled, and y_test
mae_test, r2_test, mape_test, mse_test, rmse_test = model(X_train_scaled, y_train, X_test_scaled, y_test)

print("MAE:", mae_test)
print("R2:", r2_test)
print("MAPE:", mape_test)
print("MSE:", mse_test)
print("RMSE:", rmse_test)

MAE: 2.508137353917232
R2: 0.9999036890414059
MAPE: 0.07672124248270329
MSE: 95.14304285095933
RMSE: 9.754129528100359

### LGBMRegressor

In [84]:

def model(X_train_scaled, y_train, X_test_scaled, y_test):
    
    lgb_model = LGBMRegressor()

    # Fit the model on the entire training data
    lgb_model.fit(X_train_scaled, y_train)

    # Make predictions on the testing data
    y_pred = lgb_model.predict(X_test_scaled)

    # Evaluate the model on the testing data
    mae_test = mean_absolute_error(y_test, y_pred)
    r2_test = r2_score(y_test, y_pred)
    mape_test = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    mse_test = mean_squared_error(y_test, y_pred)
    rmse_test = np.sqrt(mse_test)

    # Return the evaluation metrics
    return mae_test, r2_test, mape_test, mse_test, rmse_test


mae_test, r2_test, mape_test, mse_test, rmse_test = model(X_train_scaled, y_train, X_test_scaled, y_test)

print("MAE:", mae_test)
print("R2:", r2_test)
print("MAPE:", mape_test)
print("MSE:", mse_test)
print("RMSE:", rmse_test)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006605 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 535
[LightGBM] [Info] Number of data points in the train set: 27723, number of used features: 60
[LightGBM] [Info] Start training from score 4225.133543
MAE: 11.413095242156247
R2: 0.9997067627063133
MAPE: 0.30659698381339656
MSE: 289.6813488933735
RMSE: 17.020027875810708

c:\Users\KIIT\miniconda3\envs\elec_bill\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(